language: java
cache:
  directories:
    - ~/.m2/repository

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

install:
  mvn --settings .travis.settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_deploy:
  - mvn versions:set -DremoveSnapshot
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file: target/liquibase-s3-${project_version}.jar
  on:
    repo: miron4dev/liquibase-s3
  skip_cleanup: 'true'
  name: $project_version
  target_commitish: 'master'
  tag_name: $project_version

notifications:
  email:
    recipients:
      - miron4dev@gmail.com
    on_success: change
    on_failure: always